### ISSUE TITLE
【建议】可以把分页功能也加上

### ISSUE THREAD

**Issue by keepAwayFrom404** [Lozvoe/E-Table#4]

**Comment by keepAwayFrom404** [comment]
写得确实不错，但是能加个分页功能就完美啦

**Comment by alwynou** [comment]
> 写得确实不错，但是能加个分页功能就完美啦

已经添加

**Comment by keepAwayFrom404** [comment]
还有我看代码里面每次点开筛选面板都会重新请求数据，这里应该没有实例的时候请求，已经有了就不用请求了呢。
在headFilterBtnClick函数中。
