### ISSUE TITLE
关于输入内容的浏览器解析问题

### ISSUE THREAD

**Issue by webyangpei** [Lozvoe/E-Table#6]
![image](https://user-images.githubusercontent.com/24697986/89010544-62ac1080-d341-11ea-9204-ef7abb3151bc.png)

在编辑时输入类似 ‘List\<HH>’  这种的， 会被浏览器认为是标签 。

建议改innerHTML 为 innerText

**Comment by alwynou** [comment]
修改了，默认作为普通字符解析了
[column option](https://github.com/Lozvoe/E-Table#columns%E4%B8%AD%E5%A2%9E%E5%8A%A0%E7%9A%84%E5%B1%9E%E6%80%A7)添加了valueAsHtml属性，为true时才作为html解析

**Comment by alwynou** [comment]
> ![image](https://user-images.githubusercontent.com/24697986/89010544-62ac1080-d341-11ea-9204-ef7abb3151bc.png)
> 
> 在编辑时输入类似 ‘List<HH>’ 这种的， 会被浏览器认为是标签 。
> 
> 建议改innerHTML 为 innerText

修改了
