### ISSUE TITLE
双击编辑单元格时有没有办法保持单元格的尺寸吗？

### ISSUE THREAD

**Issue by Loong1992** [Lozvoe/E-Table#8]
@Lozvoe 您好，请教下有现在我双击单元格时，单元格会变大。请问下有什么方法可以让它保持原来的尺寸呢？
![cellsizeischange](https://user-images.githubusercontent.com/11975617/89625636-c3e85c80-d8ca-11ea-9c1e-e0a11c845821.gif)
最后再次感谢您的项目和付出！

**Comment by alwynou** [comment]
> @Lozvoe 您好，请教下有现在我双击单元格时，单元格会变大。请问下有什么方法可以让它保持原来的尺寸呢？
> ![cellsizeischange](https://user-images.githubusercontent.com/11975617/89625636-c3e85c80-d8ca-11ea-9c1e-e0a11c845821.gif)
> 最后再次感谢您的项目和付出！

可以用样式覆盖解决  本身里面也只是个input框  把这个input框的padding什么的全去了 就好了

**Comment by Loong1992** [comment]
> > @Lozvoe 您好，请教下有现在我双击单元格时，单元格会变大。请问下有什么方法可以让它保持原来的尺寸呢？
> > ![cellsizeischange](https://user-images.githubusercontent.com/11975617/89625636-c3e85c80-d8ca-11ea-9c1e-e0a11c845821.gif)
> > 最后再次感谢您的项目和付出！
> 
> 可以用样式覆盖解决 本身里面也只是个input框 把这个input框的padding什么的全去了 就好了

做到了，谢谢您的回复与指教！
